# Generated by Django 3.1 on 2022-01-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingAreaModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('attention', models.TextField()),
                ('start_usage_time', models.TimeField()),
                ('end_usage_time', models.TimeField()),
                ('postdata', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
