# Generated by Django 3.1 on 2022-01-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smokingpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmokingAreaModels',
            new_name='SmokingAreaModel',
        ),
    ]
