# Generated by Django 3.1 on 2022-01-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smokingpost', '0002_auto_20220101_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smokingareamodel',
            old_name='postdata',
            new_name='postdate',
        ),
    ]
